import {
  BadgeHelp,
  Binary,
  Bot,
  Box,
  BrainCircuit,
  ChevronRight,
  Clapperboard,
  Code2,
  Download,
  Film,
  Gamepad2,
  GitFork,
  GraduationCap,
  Layers3,
  LayoutDashboard,
  Menu,
  MonitorPlay,
  PackageCheck,
  Play,
  Rocket,
  Search,
  Sparkles,
  Volume2,
  WandSparkles,
  X,
  Zap,
} from 'lucide-react'

export const icons = {
  animation: Film,
  audio: Volume2,
  book: BadgeHelp,
  bot: Bot,
  box: Box,
  brain: BrainCircuit,
  chevron: ChevronRight,
  code: Code2,
  download: Download,
  gamepad: Gamepad2,
  github: GitFork,
  graduation: GraduationCap,
  layout: LayoutDashboard,
  menu: Menu,
  package: PackageCheck,
  physics: Zap,
  play: Play,
  rocket: Rocket,
  scene: Layers3,
  search: Search,
  sparkles: Sparkles,
  studio: MonitorPlay,
  wand: WandSparkles,
  x: X,
  clapperboard: Clapperboard,
  binary: Binary,
}

export type IconName = keyof typeof icons
